name: CD

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Deploy to dev
      uses: appleboy/ssh-action@master
      with:
        username: ${{ secrets.USERNAME }}
        host: ${{ secrets.HOST }}
        port: ${{ secrets.PORT }}
        key: ${{ secrets.KEY }}
        script: 'cd monday-hackathon && git fetch && git pull origin main && docker compose up -d --build'
